module.exports = function getCities(){
    return [
        "Sofia",
        "Plovdiv",
        "Varna",
        "Burgas",
        "Ruse",
        "Stara Zagora",
        "Pleven",
        "Shumen",
        "Kyustendil",
        "Pernik",
        "Yambol",
        "Blagoevgrad",
        "Dobrich",
        "Sliven",
        "Razgrad",
        "Haskovo",
        "Kardzhali",
        "Targovishte",
        "Smolyan",
        "Silistra",
        "Veliko Tarnovo",
        "Gabrovo",
        "Lovech",
        "Vraca",
        "Montana",
        "Vidin",
        "Pazardzhik"
    ]
} 